export interface Device {
  id: number;
  name: string;
  imei: string;
  model_nr: number,
  devicepos: number,
  deviceshow: number,
  protokoll: string;
  devicezeit: string;
  modellid: number,
  telefonnummer: string,
  kategorie: string,
  speicherdauer: number;
  intervalllaenge: number;
  status: number;
  package: any;
  createdate: string
  updatedate: string,
  spuraktiv: number,
  alarmintervall: number,
  spurmodus: number,
  spurfarbe: string;
  spurpunkte: number;
  spurminuten: number;
  spurdatum: number;
  spurdatumbis: number;
  spursymbolbewegung: number;
  spursymbolpause: number;
  alarmeinstellungenglobal: number;
  alarmbewegung: number;
  alarmbewegungintervall: number;
  alarmgeschwindigkeit: number;
  alarmgeschwindigkeitab: number;
  alarmgeschwindigkeitintervall: number;
  alarmgeozaunbefahren: number;
  alarmgeozaunbefahrenintervall: number;
  alarmgeozaunverlassen: number;
  alarmgeozaunverlassenintervall: number;
  alarmakkuwarnung: number;
  alarmakkuwarnungab: number;
  alarmakkuwarnungintervall: number;
  alarmzuendalarm: number;
  alarm_turn_off: number;
  alarm_volt: number;
  alarm_volt_value: string;
  alarmstromunterbrechung: number;
  tagesemail: number;
  alarmbewegunglastmail: number;
  alarmgeschwindigkeitlastmail: number;
  alarmgeozaunbefahrenlastmail: number;
  alarmgeozaunverlassenlastmail: number;
  alarmakkuwarnunglastmail: number;
  alarmakkucounter: number;
  alarmstromunterbrechunglastmail: number;
  alarmzuendalarmlastmail: number;
  alarmzuendalarmlastmailon: number;
  alarmzuendalarmlastmailoff: number;
  iconname: string;
  iconusecustom: number;
  iconcustomimage: string;
  radius_meter: number;
  radius_lat: string;
  radius_lng: string;
  radius_laststatus: number;
  geschwindigkeit_laststatus: number;
  zuend_laststatus: number;
  acc_lastdateunix: number;
  alarmsos: number;
  alarmsoslastmail: number;
  last_dateunix: string;
  last_datum: string;
  last_uhrzeit: string;
  last_lat_symbol: string;
  last_lng_symbol: string;
  show_kmanzeige: number;
  show_gruppenanzeigeanzeige: number;
  last_serviceport: number;
  stats_speed_active: number;
  timezone: string;
  create_dateunix:number;
  create_dateunix_str: string;
  auto_upd_date: string;
  ac_status: number;
  average_consum: string;
  selected_date_range: string;
  car_id: string;
  private_mode: number;
  carDevice_id: string;
  alarm_geofence: number;
  privacy_mode: number;
  share_link: boolean;
  loadroute: number;
  note: string;
  note_color: string;
  threedModel_name: string;
  threedModel_color: string;
  deleted_at: string;
  category_id: string;
  alarm_enabled: number;
  live_tracking_start_time: string;
  live_tracking_duration: string;
  logbook_access: number;
  device_models: any;
  appmode: any;

}